### ISSUE TITLE
new features + version bump needed

### ISSUE THREAD

**Issue by oisinlavery** [jongold/figma-js#28]
@chrisdrackett 

I've submitted a PR for a couple of new features added to the API.
Also the version wasn't bumped after the last PR was merged so npm is still stuck on 1.8.5

**Comment by chrisdrackett** [comment]
yeah, a release is needed. Sorry for the delay, I'm no longer using this project so it hasn't been top of my list to help maintain it!

**Comment by oisinlavery** [comment]
No problem Chris, thanks for merging.
