### ISSUE TITLE
Duplicate types for Vector

### ISSUE THREAD

**Issue by jem-computer** [jongold/figma-js#4]
I can't believe my eyes _and_ tslint missed this one.

We export 2 things called Vector
https://figma.com/developers/docs#vector-props
https://figma.com/developers/docs#vector-type

This is breaking the `postComment` call, which uses `client_meta: Vector` (the type, not the node).

I think perhaps a smart renaming strategy is in order - perhaps renaming _all_ of the node types to `VectorNode, LineNode` etc etc? Maybe?

This is a high priority bug inasmuch as I'm having to cast to `any` to post comments rn :D

**Comment by dvdsgl** [comment]
I renamed Vector to Vector2D in my project. I suggest not appending "Node" to all nodes.

**Comment by dvdsgl** [comment]
Actually, Vector2 could be a better name.

Another option is to use an inline record and not create a named type since so few Vector2 properties occur.
