### ISSUE TITLE
 Geometry and version options

### ISSUE THREAD

**Issue by g-a-v-i-n** [jongold/figma-js#7]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Get:file exposes no geometry or version options, but it very much should.

**Comment by jem-computer** [comment]
Looks like the Figma API changed since I last updated - would love a contribution!

**Comment by g-a-v-i-n** [comment]
I have a local branch with this working, need push auth to a new branch, then I'll make a PR

**Comment by jem-computer** [comment]
@gavinpatkinson can you create a fork and submit a PR from there?
